language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t pj/docker-react:latest

script:
  - docker run -e CI=true pj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-690299612270"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
